spring.application.name=springoteca

# Aqui eu digo para o código que o meu banco é sqlserver, a porta (padrão) que ele deve acessar e o nome do meu banco.
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=springoteca;encrypt=true;trustServerCertificate=true



spring.datasource.username=sa
spring.datasource.password=FelipeDB

# Configurações para o Hibernate atualizar minhas tabelas no sql sempre que eu atualizar minha model/
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
